[package]
name = "elsci_chemikaze"
version = "1.0.0"
edition = "2024"

[[bin]]
name = "chemikaze"
path = "src/main/rust/cli.rs"

[profile.release]
debug = true
opt-level = 3
lto = true
codegen-units = 1