use crate::errors::{ChemikazeError, ErrorKind};
use phf::{phf_map, Map};

/// They are roughly sorted by popularity in organic chemistry. Well, at least the first elements
/// are. Doesn't contain elements that would never be used in organic chemistry.
pub const EARTH_SYMBOLS: [&[u8]; 85] = [
    b"H", b"C", b"O", b"N", b"P", b"F", b"S", b"Br", b"Cl", b"Na", b"Li", b"Fe", b"K", b"Ca",
    b"Mg", b"Ni", b"Al", b"Pd", b"Sc", b"V", b"Cu", b"Cr", b"Mn", b"Co", b"Zn", b"Ga", b"Ge",
    b"As", b"Se", b"Ti", b"Si", b"Be", b"B", b"Kr", b"Rb", b"Sr", b"Y", b"Zr", b"Nb", b"Mo",
    b"Ru", b"Rh", b"Ag", b"Cd", b"In", b"Sn", b"Sb", b"Te", b"I", b"Xe", b"Cs", b"Ba", b"La",
    b"Ce", b"Pr", b"Nd", b"Sm", b"Eu", b"Gd", b"Tb", b"Dy", b"Ho", b"Er", b"Tm", b"Yb", b"Lu",
    b"Hf", b"Ta", b"Tc", b"W", b"Re", b"Os", b"Ir", b"Pt", b"Au", b"Hg", b"Tl", b"Pb", b"Bi",
    b"Th", b"Pa", b"U", b"He", b"Ne", b"Ar",
];

pub const EARTH_ELEMENT_CNT: usize = EARTH_SYMBOLS.len();

static ELEMENTS: phf::Map<&'static [u8], u8> = phf_map! {
    b"H\0" => 0,  b"C\0" => 1,  b"O\0" => 2,  b"N\0" => 3,  b"P\0" => 4,  b"F\0" => 5,  b"S\0" => 6,
    b"Br" => 7, b"Cl" => 8, b"Na" => 9, b"Li" => 10, b"Fe" => 11,
    b"K\0" => 12, b"Ca" => 13, b"Mg" => 14, b"Ni" => 15, b"Al" => 16,
    b"Pd" => 17, b"Sc" => 18, b"V\0" => 19, b"Cu" => 20, b"Cr" => 21,
    b"Mn" => 22, b"Co" => 23, b"Zn" => 24, b"Ga" => 25, b"Ge" => 26,
    b"As" => 27, b"Se" => 28, b"Ti" => 29, b"Si" => 30, b"Be" => 31,
    b"B\0" => 32,  b"Kr" => 33, b"Rb" => 34, b"Sr" => 35, b"Y\0" => 36,
    b"Zr" => 37, b"Nb" => 38, b"Mo" => 39, b"Ru" => 40, b"Rh" => 41,
    b"Ag" => 42, b"Cd" => 43, b"In" => 44, b"Sn" => 45, b"Sb" => 46,
    b"Te" => 47, b"I\0" => 48,  b"Xe" => 49, b"Cs" => 50, b"Ba" => 51,
    b"La" => 52, b"Ce" => 53, b"Pr" => 54, b"Nd" => 55, b"Sm" => 56,
    b"Eu" => 57, b"Gd" => 58, b"Tb" => 59, b"Dy" => 60, b"Ho" => 61,
    b"Er" => 62, b"Tm" => 63, b"Yb" => 64, b"Lu" => 65, b"Hf" => 66,
    b"Ta" => 67, b"Tc" => 68, b"W\0" => 69,  b"Re" => 70, b"Os" => 71,
    b"Ir" => 72, b"Pt" => 73, b"Au" => 74, b"Hg" => 75, b"Tl" => 76,
    b"Pb" => 77, b"Bi" => 78, b"Th" => 79, b"Pa" => 80, b"U\0" => 81,
    b"He" => 82, b"Ne" => 83, b"Ar" => 84,
};

#[inline(always)]
pub fn get_element_by_symbol_bytes(bytes: &[u8]) -> Result<u8, ChemikazeError> {
    match bytes {
        b"H"  => Ok(0),
        b"C"  => Ok(1),
        b"O"  => Ok(2),
        b"N"  => Ok(3),
        b"P"  => Ok(4),
        b"F"  => Ok(5),
        b"S"  => Ok(6),
        b"Br" => Ok(7),
        b"Cl" => Ok(8),
        b"Na" => Ok(9),
        b"Li" => Ok(10),
        b"Fe" => Ok(11),
        b"K"  => Ok(12),
        b"Ca" => Ok(13),
        b"Mg" => Ok(14),
        b"Ni" => Ok(15),
        b"Al" => Ok(16),
        b"Pd" => Ok(17),
        b"Sc" => Ok(18),
        b"V"  => Ok(19),
        b"Cu" => Ok(20),
        b"Cr" => Ok(21),
        b"Mn" => Ok(22),
        b"Co" => Ok(23),
        b"Zn" => Ok(24),
        b"Ga" => Ok(25),
        b"Ge" => Ok(26),
        b"As" => Ok(27),
        b"Se" => Ok(28),
        b"Ti" => Ok(29),
        b"Si" => Ok(30),
        b"Be" => Ok(31),
        b"B"  => Ok(32),
        b"Kr" => Ok(33),
        b"Rb" => Ok(34),
        b"Sr" => Ok(35),
        b"Y"  => Ok(36),
        b"Zr" => Ok(37),
        b"Nb" => Ok(38),
        b"Mo" => Ok(39),
        b"Ru" => Ok(40),
        b"Rh" => Ok(41),
        b"Ag" => Ok(42),
        b"Cd" => Ok(43),
        b"In" => Ok(44),
        b"Sn" => Ok(45),
        b"Sb" => Ok(46),
        b"Te" => Ok(47),
        b"I"  => Ok(48),
        b"Xe" => Ok(49),
        b"Cs" => Ok(50),
        b"Ba" => Ok(51),
        b"La" => Ok(52),
        b"Ce" => Ok(53),
        b"Pr" => Ok(54),
        b"Nd" => Ok(55),
        b"Sm" => Ok(56),
        b"Eu" => Ok(57),
        b"Gd" => Ok(58),
        b"Tb" => Ok(59),
        b"Dy" => Ok(60),
        b"Ho" => Ok(61),
        b"Er" => Ok(62),
        b"Tm" => Ok(63),
        b"Yb" => Ok(64),
        b"Lu" => Ok(65),
        b"Hf" => Ok(66),
        b"Ta" => Ok(67),
        b"Tc" => Ok(68),
        b"W"  => Ok(69),
        b"Re" => Ok(70),
        b"Os" => Ok(71),
        b"Ir" => Ok(72),
        b"Pt" => Ok(73),
        b"Au" => Ok(74),
        b"Hg" => Ok(75),
        b"Tl" => Ok(76),
        b"Pb" => Ok(77),
        b"Bi" => Ok(78),
        b"Th" => Ok(79),
        b"Pa" => Ok(80),
        b"U"  => Ok(81),
        b"He" => Ok(82),
        b"Ne" => Ok(83),
        b"Ar" => Ok(84),
        _ => Err(ChemikazeError {
            msg: format!(
                "Unknown chemical symbol: {}",
                std::str::from_utf8(bytes).unwrap_or("<invalid>")
            ),
            kind: ErrorKind::UnknownElement,
        }),
    }
}

